VYZNAM_LEGENDA = [
    [
        "Následok",
        "Kritériá pre určenie významnosti z hľadiska následku pre zákazníka / používateľa",
        "Kritériá pre určenie významnosti z hľadiska následku pre proces / organizáciu",
        "Hodnota indexu",
    ],
    [
        "Nebezpečný - bez varovania",
        "Veľmi vysoké hodnotenie významnosti, keď možná chyba výrazne ovplyvní bezpečnosť, zdravie, súlad s požiadavkami alebo spôsobí kritické zlyhanie bez predchádzajúceho varovania.",
        "Môže ohroziť pracovníka, zariadenie, prevádzku alebo viesť ku kritickému prerušeniu procesu bez varovania.",
        10,
    ],
    [
        "Nebezpečný - s varovaním",
        "Veľmi vysoké hodnotenie významnosti, keď možná chyba výrazne ovplyvní bezpečnosť, zdravie, súlad s požiadavkami alebo spôsobí kritické zlyhanie s predchádzajúcim varovaním.",
        "Môže ohroziť pracovníka, zariadenie alebo prevádzku, avšak s predchádzajúcim varovaním.",
        9,
    ],
    [
        "Veľmi vážny",
        "Produkt, služba alebo výstup procesu je nefunkčný alebo dochádza k strate základnej funkcie.",
        "100 % výstupov môže byť vyradených, proces sa zastaví alebo je potrebný zásah iného útvaru s významnou časovou stratou.",
        8,
    ],
    [
        "Vážny",
        "Produkt, služba alebo výstup procesu zostáva funkčný, ale s výrazne zníženou úrovňou výkonnosti. Používateľ je veľmi nespokojný.",
        "Časť výstupov musí byť vyradená alebo prepracovaná, prípadne je potrebný zásah iného útvaru so strednou časovou stratou.",
        7,
    ],
    [
        "Mierny",
        "Funkčnosť zostáva zachovaná, ale niektoré vlastnosti, komfort alebo použiteľnosť sú obmedzené. Používateľ je nespokojný.",
        "Časť výstupov musí byť vyradená alebo prepracovaná s menším dopadom na priebeh procesu.",
        6,
    ],
    [
        "Malý",
        "Výstup je funkčný, ale so zníženou účinnosťou alebo nižšou kvalitou bez zásadného dopadu na základnú funkciu.",
        "Výstupy musia byť prepracované mimo hlavného miesta vykonania operácie, ale bez zásadného narušenia procesu.",
        5,
    ],
    [
        "Veľmi malý",
        "Používateľ si všimne menší nedostatok kvality, vzhľadu, presnosti alebo komfortu. Vadu si všimne väčšina používateľov.",
        "Výstupy musia byť pretriedené alebo čiastočne prepracované bez zásadného dopadu na chod procesu.",
        4,
    ],
    [
        "Nevýznamný",
        "Používateľ si všimne drobný nedostatok len v časti prípadov.",
        "Menšia časť výstupov si vyžaduje lokálnu úpravu alebo opravu bez výrazného dopadu na proces.",
        3,
    ],
    [
        "Úplne nevýznamný",
        "Nedostatok je sotva rozpoznateľný a ovplyvňuje len malú časť používateľov alebo situácií.",
        "Dopad na proces je zanedbateľný a ľahko odstrániteľný na mieste.",
        2,
    ],
    [
        "Žiadny",
        "Bez rozpoznateľného následku pre zákazníka alebo používateľa.",
        "Bez rozpoznateľného následku pre proces, organizáciu alebo pracovníka.",
        1,
    ],
]


VYSKYT_LEGENDA = [
    [
        "Pravdepodobnosť výskytu chyby",
        "Možná početnosť chýb",
        "Ppk (Cpk)",
        "Hodnota indexu",
    ],
    ["Veľmi vysoká: Chyba sa vyskytuje permanentne", "> 100 z 1000", "<0,55", 10],
    ["Veľmi vysoká: Chyba sa vyskytuje permanentne", "50 z 1000", ">0,55", 9],
    ["Vysoká: Opakovaný výskyt chyby", "20 z 1000", ">0,78", 8],
    ["Vysoká: Opakovaný výskyt chyby", "10 z 1000", ">0,86", 7],
    ["Priemerná: Občasný výskyt chyby", "5 z 1000", ">0,94", 6],
    ["Priemerná: Občasný výskyt chyby", "2 z 1000", ">1,00", 5],
    ["Priemerná: Občasný výskyt chyby", "1 z 1000", ">1,10", 4],
    ["Nízka: Relatívne malý výskyt chyby", "0,5 z 1000", ">1,20", 3],
    ["Nízka: Relatívne malý výskyt chyby", "0,1 z 1000", ">1,30", 2],
    ["Nepatrná: Chyba je nepravdepodobná", "0,01 z 1000", ">1,67", 1],
]


ODHALENIE_LEGENDA = [
    [
        "Odhalenie",
        "Kritérium",
        "Typ kontroly A",
        "Typ kontroly B",
        "Typ kontroly C",
        "Predpokladaný rozsah kontroly",
        "Hodnota indexu",
    ],
    [
        "Prakticky nemožné",
        "Prakticky istota, že sa chyba neodhalí",
        "",
        "",
        "X",
        "Chybu nie je možné odhaliť alebo nie je zavedená vhodná kontrola.",
        10,
    ],
    [
        "Veľmi nepatrná možnosť",
        "Pravdepodobne neodhalí",
        "",
        "",
        "X",
        "Nepriama, náhodná alebo neúplná kontrola.",
        9,
    ],
    [
        "Nepatrná možnosť",
        "Malá šanca odhaliť",
        "",
        "",
        "X",
        "Iba jednoduchý vizuálny spôsob kontroly.",
        8,
    ],
    [
        "Veľmi malá možnosť",
        "Malá šanca odhaliť",
        "",
        "",
        "X",
        "Opakovaná vizuálna alebo manuálna kontrola s obmedzenou spoľahlivosťou.",
        7,
    ],
    [
        "Malá možnosť",
        "Môže odhaliť",
        "",
        "X",
        "X",
        "Grafický záznam, trendovanie alebo štatistické sledovanie procesu.",
        6,
    ],
    [
        "Priemerná možnosť",
        "Môže odhaliť",
        "",
        "X",
        "",
        "Kontrola meraním parametra alebo 100 % kontrola výstupu po vykonaní operácie.",
        5,
    ],
    [
        "Nadpriemerná možnosť",
        "Dobrá šanca odhaliť",
        "X",
        "X",
        "",
        "Kontrola na nasledujúcom kroku procesu alebo kontrola po nastavení a prvom kuse.",
        4,
    ],
    [
        "Veľká možnosť",
        "Dobrá šanca odhaliť",
        "X",
        "X",
        "",
        "Kontrola na pracovnom mieste alebo na nasledujúcom kroku s viacnásobným overením. Chybný výstup sa s vysokou pravdepodobnosťou neprepustí ďalej.",
        3,
    ],
    [
        "Veľmi veľká možnosť",
        "Väčšinou istota, že odhalí",
        "X",
        "X",
        "",
        "Automatické meranie alebo automatická kontrola so zastavením procesu pri výskyte chyby.",
        2,
    ],
    [
        "Veľmi veľká možnosť",
        "Väčšinou istota, že odhalí",
        "X",
        "",
        "",
        "Chyba prakticky nemôže vzniknúť, pretože jej bráni konštrukcia riešenia, technické zabezpečenie alebo princíp poka-yoke.",
        1,
    ],
]